#!/bin/sh

case "${@}" in
	*-print-file-name=*)
		dirs="$(${HOSTCC_REAL} -print-search-dirs | grep -m1 libraries | sed -e 's,:, ,' -e 's,.* =,,')"
		dirs="${dirs} /usr/lib /usr/local/lib"
		find ${dirs} -name "${1#*=}" | head -n1
	;;
	*-x\ ada*)
		exit 1
	;;
	*)
		exec "${HOSTCC_REAL}" "${@}"
	;;
esac
